### ISSUE TITLE
Inkscape Figure Manager Failed

### ISSUE THREAD

**Issue by Xuer04** [sleepymalc/VSCode-LaTeX-Inkscape#22]
I have replaced all the inkscapefigures files with yours, but I still can't make it available, when I type 'inkscape-figures watch' in terminal or use 'C-f' in VsCode with VISUAL mode, nothing happened, without the error 'Unable to lock on the pidfile.'. After I create a figure with inkscape and save it. There is just one file called *.svg without other two files. I can't find some way to solve it, may I have some methods to check whether the 'inkscapefigures' works?

My OS: macos Ventura 13.1(M2)
Inkscape Version: 1.2.2

**Comment by Xuer04** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/80182956/221107683-01bd3134-a51f-4bca-98bb-6670175c47f6.png">

**Comment by sleepymalc** [comment]
Can you try to execute this in `Code/tex/Report` instead of `Code/tex/Report/Figures`? Also, to check whether `inkscape-figures` works, maybe try `which inkscape-figures`.

**Comment by Xuer04** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/80182956/221110143-fb0824e3-c774-4eda-9e3f-81a8160ae3b7.png">

Same as before. :(

**Comment by sleepymalc** [comment]
Have you tried restarting your laptop?

**Comment by Xuer04** [comment]
Yeah, I have restarted my laptop twice, the situation is what above like.

**Comment by sleepymalc** [comment]
This is quite weird. Can you run `inkscape-figures --help`?

**Comment by Xuer04** [comment]
Yeah, but the command `inkscape-figures watch` still takes no effect.

**Comment by sleepymalc** [comment]
In this case I really don't know how to proceed... I guess you might need to directly modify the `watch` function in `inkscapefigures/main.py` to directly debug...

**Comment by Xuer04** [comment]
Thanks, I will have a try.

**Comment by sleepymalc** [comment]
Maybe tried `brew install fswatch`? I found this [here](https://github.com/gillescastel/inkscape-figures/issues/31).
