### ISSUE TITLE
Shortcuts not working

### ISSUE THREAD

**Issue by vikomen** [sleepymalc/VSCode-LaTeX-Inkscape#26]
Hi, thank you for the wonderfull guide. I am a vim user on macos who is trying to get the shortcuts working independently.  I followed the steps in the installation (althought I had some issues with hs) but none of the shortcuts seem to work. I have both Karabiner ellements and Hammerspoon oppened with the desired configs. Any recomendations as how to trouble shoot this?

**Comment by sleepymalc** [comment]
Have you tried restarting your laptop?

**Comment by vikomen** [comment]
Yes. As I mentioned I think it is an hs issue as the original way of installing didn't work for me, I had to use a workaround. When I open the client it seems to work but there could be path issues with the script. Any ideas how to diagnose this?

**Comment by sleepymalc** [comment]
I'm unfamiliar with Hammerspoon (I only use it for this shortcut manager). So I'm afraid that I can't help much. It might be helpful to provide what exactly the workaround you use.

**Comment by vikomen** [comment]
I followed this issue https://github.com/Hammerspoon/hammerspoon/issues/2930. I got it to install via hs.ipc.cliInstall("/opt/homebrew"). I think that it has installed because when I write hs in the client I am getting suggestions. However, when I now try hs.ipc.cliInstall() I get

2023-10-09 00:41:43: -- Loading extension: ipc
false

This leads me to believe that something has gone wrong.

**Comment by sleepymalc** [comment]
Have you tried [this](https://github.com/Hammerspoon/hammerspoon/issues/2930#issuecomment-899092002)? I mean this seems more like a hs issue, not this project's issue.
