### ISSUE TITLE
Fail to identify the math mode and text mode

### ISSUE THREAD

**Issue by zhan-gao** [sleepymalc/VSCode-LaTeX-Inkscape#28]
Thank you so much @sleepymalc for the fantastic contribution! I've been enjoying this Latex setup except for one thing.

Sometimes my VS code starts to fail to identify whether I'm in text mode or math mode, and suddenly all math snippets apply everywhere. This goes away if I close and reopen the file.

Another issue is that when I insert labels in equations it is identified as math mode in \label{}. 

Thank you very much in advance if you have thoughts about these issues.

**Comment by sleepymalc** [comment]
For the first issue, see #25; for the second, there are no special scopes for `\label{ }`. This is a common issue that I also faced, and my solution would be to create these labels outside the math environment and then cut-paste them to the correct place.

**Comment by zhan-gao** [comment]
Thanks so much.
