### ISSUE TITLE
Does this setup work with LatexWorkshop?

### ISSUE THREAD

**Issue by anandkumar89** [sleepymalc/VSCode-LaTeX-Inkscape#32]
I've installed hyper snips and copied the latex.snips to correct path. I also have LatexWorkshop installed. 

many of commands in .snips doesn't seem to activate. Also context doesn't seem to work. Any help would be appreciated.

I use obsidian with latexSuite and shortcuts mentioned there are awesome. Wanted something similar in vs-code.

**Comment by sleepymalc** [comment]
Definitely, as it's meant to be used together with LaTeX-Workshop. The information you provide is not enough for me to make any guess. But I think one thing you might want to check is to first try some naive snippets and see how it works.

**Comment by sleepymalc** [comment]
The context matching is not perfect as the scope will sometimes fail without reasons. You'll need to manually reload scope for this reason.
<img width="411" alt="image" src="https://github.com/sleepymalc/VSCode-LaTeX-Inkscape/assets/60427058/f032d965-94e3-4504-b7aa-d0da18b020bd">
