### ISSUE TITLE
Some updates

### ISSUE THREAD

**Issue by mooxiu** [sleepymalc/VSCode-LaTeX-Inkscape#35]
Hi, thanks for your instructions!

During my setup, I found there is something that has changed in vscode, so I would like to post it here:

### Creating snippets file:

> Type snippets, and choose Preferences: Configure User Snippets.
Should be choose `Snippets: Configure Snippets` now

### HyperSnips location:

> Please first download [HyperSnips](https://marketplace.visualstudio.com/items?itemName=draivin.hsnips) and just follow the instructions, copy [latex.hsnips](https://github.com/sleepymalc/VSCode-LaTeX-Inkscape/blob/main/main/VSCode-setting/Snippets/latex.hsnips) into $HOME/Library/Application Support/Code/User/hsnips/, and you're good to go!

For `HyperSnips v0.2.9`, the locations becomes:
`$HOME/Library/Application Support/Code/User/globalStorage/draivin.hsnips/hsnips/(language).hsnips`

Also, `latex.hsnips` of this repository should point to [here](https://github.com/sleepymalc/VSCode-LaTeX-Inkscape/blob/main/VSCode-setting/Snippets/latex.hsnips) rather than [here](https://github.com/sleepymalc/VSCode-LaTeX-Inkscape/blob/main/main/VSCode-setting/Snippets/latex.hsnips).

---

My vscode version info:
```
Version: 1.94.2 (Universal)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0
```

**Comment by mooxiu** [comment]
I can make a PR if it's OK

**Comment by sleepymalc** [comment]
Sure, you're welcome to do that.
